### PR TITLE
Xcode 12 updates.

### PR DESCRIPTION
**Pull request by LaurentiuUngur**

### CODE REVIEW

**Comment by krimpedance** [comment]
@LaurentiuUngur 
Thank you for PR.
But, you can't change versions.
So please undo these changes, and create new PR (with clean commits).

**Comment by LaurentiuUngur** [comment]
@krimpedance Thanks, I will. What is the minimum iOS version it should support ? iOS 9 and 10 I think it's too old

**Comment by krimpedance** [comment]
@LaurentiuUngur 
Some apps have to support older versions, so you shouldn't change that.

**Comment by LaurentiuUngur** [comment]
If dropping very old iOS versions is not allowed, then there's no point in creating another PR.

**Pull request closed without merging**
